# Site settings
title: Charles Harley
tagline: 'Sharing is Caring'
description: ""
baseurl: ""
url: "http://charlesharley.com"
timezone: Europe/London
username: charlesharley

# Build settings
markdown: kramdown
include: ['_pages']
permalink: /:year/:categories/:title

kramdown:
  input: GFM
