# Site settings
title: Charles Harley
tagline: 'Sharing is Caring'
description: ""
baseurl: ""
url: "http://charlesharley.com"
timezone: Europe/London

# Build settings
markdown: kramdown
permalink: /:year/:categories/:title

kramdown:
  input: GFM
